// ════════════════════════════════════════════════════════════════
//  PAINEL DE CONFIGURAÇÃO DO SITE
//  Edite este arquivo e dê "git push" para alterar o site.
// ════════════════════════════════════════════════════════════════

export const site = {
  name: 'Oratório Digital',
  tagline: 'Um espaço para rezar com calma — orações, terços e novenas.',
  defaultLang: 'pt-BR' as const,

  // ── Contador da comunidade (serviço Abacus, grátis, sem cadastro) ──
  // IMPORTANTE: troque o namespace por algo ÚNICO seu (3–64 caracteres,
  // letras/números/._-) para seu contador não se misturar com o de outra
  // pessoa. Ex.: 'oratorio-do-joao-2026'.
  counter: {
    enabled: true,
    base: 'https://abacus.jasoncameron.dev',
    namespace: 'oratorio-digital-EXEMPLO-troque-isto',
    totalKey: 'total', // chave do contador global somado de todas as orações
  },

  // ── CAPTCHA anti-bot (Cloudflare Turnstile) — OPCIONAL ──
  // Deixe siteKey vazio para desativar (o botão "Concluir" funciona sem ele,
  // com proteção simples de 1x por dia por oração). Para ativar, crie um
  // widget grátis em https://dash.cloudflare.com → Turnstile e cole a chave.
  turnstile: {
    siteKey: '', // ex.: '0x4AAAAAAA...'
  },

  // ── Destaques fixos na home (orações sempre em evidência) ──
  // Use o "id" do arquivo .md (nome do arquivo sem .md).
  pinnedPrayers: [
    { id: 'pai-nosso', order: 1 },
    { id: 'ave-maria', order: 2 },
    { id: 'terco', order: 3 },
    { id: 'dezena', order: 4 },
    { id: 'rosario', order: 5 },
  ],

  // Quantos destaques litúrgicos automáticos mostrar de uma vez
  maxLiturgicalHighlights: 3,

  showCommunityCounter: true,
};

// ── Textos da interface (i18n leve). Adicione idiomas aqui. ──
export const ui = {
  'pt-BR': {
    langLabel: 'Português',
    nav_home: 'Início',
    nav_catalog: 'Catálogo',
    hero_kicker: 'Reze com calma',
    community_pre: 'Esse site já guiou',
    community_post: 'orações, ajudando a iluminar nosso mundo.',
    count_tap: 'toque para contar',
    times_prayed: 'vezes que esta oração já foi rezada',
    count_short: 'vezes rezada',
    today_seal: 'Oração do dia',
    today_cta: 'Rezar agora',
    today_begin: 'Comece hoje esta novena',
    pinned_title: 'Orações do dia a dia',
    catalog_title: 'Catálogo',
    search_placeholder: 'Buscar oração, novena ou santo…',
    filter_all: 'Todas',
    show_more: 'Mostrar mais',
    filter_today: 'Hoje',
    filter_week: 'Essa semana',
    filter_month: 'Este mês',
    lbl_type: 'Tipo',
    lbl_date: 'Data',
    lbl_lang: 'Idioma',
    nav_feasts: 'Próximas festas',
    favorites_title: 'Minhas orações',
    fav_save: 'Salvar',
    fav_saved: 'Salvo',
    share: 'Compartilhar',
    link_copied: 'Link copiado!',
    focus_mode: 'Foco',
    feasts_title: 'Próximas festas',
    feasts_lead: 'Acompanhe as celebrações e novenas ao longo do ano.',
    feasts_empty: 'Nenhuma festa cadastrada ainda.',
    novena_active: 'novena em andamento',
    novena_from: 'novena começa em',
    nav_bio: 'Biografias',
    bio_title: 'Biografias',
    bio_lead: 'Vidas de santos, mártires e testemunhas da fé.',
    bio_empty: 'As biografias serão publicadas em breve.',
    bio_born: 'Nascimento',
    bio_died: 'Falecimento',
    bio_feast: 'Festa litúrgica',
    bio_patron: 'Padroeiro de',
    bio_related: 'Orações relacionadas',
    bio_read: 'Ler biografia',
    fav_bio_title: 'Minhas biografias',
    bio_search_placeholder: 'Buscar santo, título ou padroado…',
    lbl_category: 'Categoria',
    bio_no_results: 'Nenhuma biografia encontrada.',
    global_search_ph: 'Buscar orações e santos…',
    global_search_hint: 'Digite para buscar orações e biografias.',
    search_kind_bio: 'Biografia',
    bio_about: 'Conheça a vida de',
    santo_today: 'Santo do dia',
    santo_next: 'Próximo santo',
    season_advento: 'Tempo do Advento',
    season_natal: 'Tempo do Natal',
    season_quaresma: 'Tempo da Quaresma',
    season_pascoa: 'Tempo Pascal',
    season_comum: 'Tempo Comum',
    season_pentecostes: 'Pentecostes',
    share_image: 'Imagem',
    cat_martir: 'Mártir',
    cat_doutor: 'Doutor da Igreja',
    cat_virgem: 'Virgem',
    cat_bispo: 'Bispo',
    cat_papa: 'Papa',
    cat_apostolo: 'Apóstolo',
    cat_anjo: 'Anjo',
    cat_diacono: 'Diácono',
    cat_religioso: 'Religioso(a)',
    cat_fundador: 'Fundador(a)',
    cat_profeta: 'Profeta',
    cat_vidente: 'Vidente',
    cat_realeza: 'Realeza',
    cat_maria: 'Nossa Senhora',
    filter_type: 'Tipo',
    filter_lang: 'Idioma',
    type_oracao: 'Oração',
    type_novena: 'Novena',
    type_rosario: 'Rosário',
    type_terco: 'Terço',
    type_dezena: 'Dezena',
    type_ladainha: 'Ladainha',
    type_hino: 'Hino',
    type_devocional: 'Devocional',
    type_liturgia: 'Liturgia',
    type_bizantina: 'Bizantina',
    type_outro: 'Outro',
    no_results: 'Nenhuma oração encontrada com esses filtros.',
    open: 'Abrir',
    day: 'Dia',
    day_of: 'de',
    reading_assistant: 'Assistente de leitura',
    speed: 'Ritmo',
    speed_slow: 'Lento',
    speed_medium: 'Médio',
    speed_fast: 'Rápido',
    start: 'Iniciar',
    pause: 'Pausar',
    resume: 'Continuar',
    restart: 'Reiniciar',
    next: 'Próximo',
    finish_prayer: 'Concluir oração',
    finishing: 'Registrando…',
    completed_title: 'Oração concluída',
    completed_sub: 'Você faz parte de uma corrente de oração.',
    total_now: 'orações no total',
    next_day: 'Próximo dia',
    pray_again: 'Rezar de novo',
    back_catalog: 'Voltar ao catálogo',
    days_to_feast: 'dias para a festa',
    feast_today: 'A festa é hoje!',
    suggested_day: 'comece pelo',
    captcha_needed: 'Confirme que você não é um robô para registrar.',
    progress_saved: 'Progresso salvo neste aparelho.',
  },
  en: {
    langLabel: 'English',
    nav_home: 'Home',
    nav_catalog: 'Catalog',
    hero_kicker: 'Pray with calm',
    community_pre: 'This site has already guided',
    community_post: 'prayers, helping to light up our world.',
    count_tap: 'tap to count',
    times_prayed: 'times this prayer has been prayed',
    count_short: 'times prayed',
    today_seal: 'Prayer of the day',
    today_cta: 'Pray now',
    today_begin: 'Begin this novena today',
    pinned_title: 'Everyday prayers',
    catalog_title: 'Catalog',
    search_placeholder: 'Search a prayer, novena or saint…',
    filter_all: 'All',
    show_more: 'Show more',
    filter_today: 'Today',
    filter_week: 'This week',
    filter_month: 'This month',
    lbl_type: 'Type',
    lbl_date: 'Date',
    lbl_lang: 'Language',
    nav_feasts: 'Upcoming feasts',
    favorites_title: 'My prayers',
    fav_save: 'Save',
    fav_saved: 'Saved',
    share: 'Share',
    link_copied: 'Link copied!',
    focus_mode: 'Focus',
    feasts_title: 'Upcoming feasts',
    feasts_lead: 'Follow the celebrations and novenas through the year.',
    feasts_empty: 'No feasts yet.',
    novena_active: 'novena in progress',
    novena_from: 'novena begins',
    nav_bio: 'Biographies',
    bio_title: 'Biographies',
    bio_lead: 'Lives of saints, martyrs and witnesses of the faith.',
    bio_empty: 'Biographies will be published soon.',
    bio_born: 'Born',
    bio_died: 'Died',
    bio_feast: 'Feast day',
    bio_patron: 'Patron of',
    bio_related: 'Related prayers',
    bio_read: 'Read biography',
    fav_bio_title: 'My biographies',
    bio_search_placeholder: 'Search saint, title or patronage…',
    lbl_category: 'Category',
    bio_no_results: 'No biographies found.',
    global_search_ph: 'Search prayers and saints…',
    global_search_hint: 'Type to search prayers and biographies.',
    search_kind_bio: 'Biography',
    bio_about: 'Discover the life of',
    santo_today: 'Saint of the day',
    santo_next: 'Next saint',
    season_advento: 'Advent',
    season_natal: 'Christmas Time',
    season_quaresma: 'Lent',
    season_pascoa: 'Eastertide',
    season_comum: 'Ordinary Time',
    season_pentecostes: 'Pentecost',
    share_image: 'Image',
    cat_martir: 'Martyr',
    cat_doutor: 'Doctor of the Church',
    cat_virgem: 'Virgin',
    cat_bispo: 'Bishop',
    cat_papa: 'Pope',
    cat_apostolo: 'Apostle',
    cat_anjo: 'Angel',
    cat_diacono: 'Deacon',
    cat_religioso: 'Religious',
    cat_fundador: 'Founder',
    cat_profeta: 'Prophet',
    cat_vidente: 'Visionary',
    cat_realeza: 'Royalty',
    cat_maria: 'Our Lady',
    filter_type: 'Type',
    filter_lang: 'Language',
    type_oracao: 'Prayer',
    type_novena: 'Novena',
    type_rosario: 'Rosary',
    type_terco: 'Chaplet',
    type_dezena: 'Decade',
    type_ladainha: 'Litany',
    type_hino: 'Hymn',
    type_devocional: 'Devotional',
    type_liturgia: 'Liturgy',
    type_bizantina: 'Byzantine',
    type_outro: 'Other',
    no_results: 'No prayers match these filters.',
    open: 'Open',
    day: 'Day',
    day_of: 'of',
    reading_assistant: 'Reading assistant',
    speed: 'Pace',
    speed_slow: 'Slow',
    speed_medium: 'Medium',
    speed_fast: 'Fast',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    restart: 'Restart',
    next: 'Next',
    finish_prayer: 'Complete prayer',
    finishing: 'Recording…',
    completed_title: 'Prayer completed',
    completed_sub: 'You are part of a chain of prayer.',
    total_now: 'prayers in total',
    next_day: 'Next day',
    pray_again: 'Pray again',
    back_catalog: 'Back to catalog',
    days_to_feast: 'days to the feast',
    feast_today: 'The feast is today!',
    suggested_day: 'start on',
    captcha_needed: 'Confirm you are not a robot to record it.',
    progress_saved: 'Progress saved on this device.',
  },
} as const;

export type Lang = keyof typeof ui;

// Prefixa o caminho-base do site (para funcionar em GitHub Pages /repo/).
export function withBase(path: string): string {
  const base = import.meta.env.BASE_URL.replace(/\/$/, '');
  if (!path) return base || '/';
  if (/^https?:\/\//.test(path)) return path; // URL externa
  return base + (path.startsWith('/') ? path : '/' + path);
}
